export default {
  HOME: '/',
  CHOOSE_STACKING_METHOD: '/choose-stacking-method',
  START_POOLED_STACKING: '/start-pooled-stacking',
  START_DIRECT_STACKING: '/start-direct-stacking',
  DIRECT_STACKING_INFO: '/direct-stacking-info',
  POOLED_STACKING_INFO: '/pooled-stacking-info',
  LOCK_MORE: '/lock-more',
  SELF_SERVICE_EXTEND: '/self-service-extend',
  SETTINGS_NETWORK: '/settings/network',
  ADD_NETWORK: '/settings/add-network',
  DELEGATE_STACK_STX: '/pool-admin/delegate-stack-stx',
  DELEGATE_STACK_INCREASE: '/pool-admin/delegate-stack-increase',
  DELEGATE_STACK_EXTEND: '/pool-admin/delegate-stack-extend',
  STACK_AGGREGATION_COMMIT: '/pool-admin/stack-aggregation-commit',
};
